# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Geordie Hess
title: Senior Software Engineer
email: geordiehess44@gmail.com
# website: https://geordiehess44.github.io/resume2020

# Social links
twitter_username: geordiehess
github_username:  geordiehess44
# dribbble_username: jekyll
facebook_username: geordiehess
# flickr_username: jekyll
instagram_username: geordie.hess
linkedin_username: george-hess-1461206
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Driven, productive, and effective <mark>engineering manager</mark> with 20 years of experience in the technology sector, 
  ranging from start-ups to enterprise level organizations.  I have been Managing and developing applications 
  and services in the telecome and daily deals industries, serving across all business functions including, but
  not limited to sales, sales operations, customer service, finance, marketing, and HR.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering and leadership some of my other interests and hobbies are:
   - Golf
   - Family
   - Craft Beers

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
